// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@2.4.0_vite@6.3.2_vue@3.5.13/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@2.4.0_vite@6.3.2_vue@3.5.13/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.16.2_@types+node@22.14.1_eslint@9.25.0_rollup@4.40.0_typescript@5.8.3_vite@6.3.2_vue-tsc@2.2.8/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/vue-list.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
